name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        npm install
        npm run build
      env:
        PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist